### ISSUE TITLE
1. duplicate and clone

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#1]
Task to complete:

- [x] move bnb to new server on softlayer.com

- [x] remove all properties from website

- [ ] -adjust json tags to catgeory website

- [x] rename cateories ie villas, cottage to 3 categories and delete the rest 1. Escorts 2.Strip clubs 3. Massage Parlors

- [ ] Get Marco lang text file so I can rename all text to relevant text

**Comment by mindrootstech** [comment]
i was able to login into softlayer successfully.
Will need access to domain so it can be pointed to server.

Tasks to be done will be:
1. Setup LAMP environment on server
2. Export all codebase from bnbfusion and setup on new server
3. Clear all listings on new server
4. Change categories to new provided categories

Plus will provide the language file.
Didnt understand what you meant by * adjust json tags to catgeory website

Rest of the tasks will be $300 to complete.
Please approve

**Comment by mnights101** [comment]
Manik, We will not be hosting this website on softlayer. Instead we will host on liquidweb LAMP eviroment already setup. Please requote

cpanel login will be sent via whatsapp

**Comment by mnights101** [comment]
json tags are for the SEO tags you added and we will change it from accommodations to website

**Comment by mindrootstech** [comment]
Since the server is already setup, Task 1 is no longer needed.
So revised quote for the Points 2,3,4,5 will be $200.
Please approve.

**Comment by mindrootstech** [comment]
Done.
http://erosradar.com/ is functional now and User/listing database has been cleared and property types have been updated.

**Comment by mnights101** [comment]
4. this task seems to be pending
![2019-02-26_09-32-32](https://user-images.githubusercontent.com/10249755/53417396-df4bfa00-39ab-11e9-92e8-be43c1faac71.png)

**Comment by mindrootstech** [comment]
This has also been resolved and updated now.

**Comment by mnights101** [comment]
PAID via upwork milestone 22
