### ISSUE TITLE
cannot update site settings for analytics

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#11]
I cannot seem to add analytcis code to site settings analytics:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-45571390-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-45571390-2');
</script>

**Comment by mindrootstech** [comment]
Code setup done.
Effort - $10

**Comment by mnights101** [comment]
paid via upwork milestone 28
