### ISSUE TITLE
install tag manager 

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#12]
- [ ] Copy the code below and paste it onto every page of your website.

Paste this code as high in the <head> of the page as possible:

`
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5Z39RLD');</script>
`

- [ ] Additionally, paste this code immediately after the opening <body> tag:

`
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5Z39RLD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
`

**Comment by mindrootstech** [comment]
Code added
Effort - $10

**Comment by mnights101** [comment]
paid via milestone 12
