### ISSUE TITLE
add Exoclick tag html

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#15]
Place meta tag in the <head> section of the web page: https://erosradar.com

<meta name="exoclick-site-verification" content="d283b747327a0809ba591b70fff16b17">

**Comment by mnights101** [comment]
<meta name="exoclick-site-verification" content="d283b747327a0809ba591b70fff16b17">

**Comment by mindrootstech** [comment]
The metatag has been added to the website.
Please check and confirm.
