### ISSUE TITLE
Need custom links for site links

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#17]
Please create these pages with exact URL and point them to category specified:

1. https://www.erosradar.com/escorts-near-me  - point to home page with escort selected in drop down

2. https://www.erosradar.com/massage-parlos-near-me - point to home page with massage drop down selected

3. https://www.erosradar.com/reviews - point to sitemap page

4. https://www.erosradar.com/strip-clubs-near-me - point to home page with strip club dropdown selected

**Comment by mindrootstech** [comment]
Marco,

The task has been completed on live and all 4 links are working now.
We have implemented a fallback. If in case the IP based address isn't searchable, we fallback to showing all listings in US.
Please check and verify.

Effort: $140

**Comment by mnights101** [comment]
They all seem to point to massage category, they should adjust to respective category

**Comment by mnights101** [comment]
funded via upwork, waiting on error fix to release milestone # 30

**Comment by mindrootstech** [comment]
The URLs are pointing to the right categories now.

**Comment by mnights101** [comment]
PAID VIA Upwork milestone #30
