### ISSUE TITLE
Sign up welcome box fix

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#19]
the welcome box displays irrelevant text, please change to this

"Welcome
Providers and clients on site are real people with real services and business locations. That is why you will have to confirm your email address before you can add a new listing. Please check your email to verify."

![fix-welcome-message](https://user-images.githubusercontent.com/10249755/66513283-c14d8880-eaa8-11e9-9f3b-d8dcf74fa1ae.jpg)

**Comment by subodhsri1** [comment]
Hourly Estimate: 1.5 Hours

**Comment by mindrootstech** [comment]
This task is also already completed @mnights101

**Comment by mnights101** [comment]
QA checked issue completed
