### ISSUE TITLE
2. upload content csv to respective category

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#2]

**Comment by mindrootstech** [comment]
Hi Marco,

As requested, we will start with the strippers data import.
Tasks to be done:
1. On home page and in inner search, implement a type dropdown with selection for strippers, clubs and escorts.
2. Show Filters and results in search page acc to type selected
3. Import data from strippers spreadsheet acc to data format and create filter fields as per adultsearch.com
4. Create a separate script to scrap off images from URL and save them in S3 bucket 
5. Dynamically show data on listing details page as per the type.

NOTE - Other sections of the site (like admin panel, My account, Create listing etc) might be effected once the data is imported but its difficult to scope all of them out at this point. Once we chnge the db structure and import this data, then we can look at the other parts that need further work and scope them separately.

Effort: $450
Additional effort to import rest of the 2 categories will be $280 per sheet as all 3 have entirely different data sets and filter settings.

**Comment by mindrootstech** [comment]
Marco,

All the 3 data sheets have been imported.
Images are in the process of being scrapped as the script is running.
Meanwhile, you can review the data for all the 3 categories so we can proceed further.

**Comment by mnights101** [comment]
can we get the strip clubs and massage parlors appear properly on the map as they do have addresses? maybe a script to convert listed address into gps coordinate?

we can make this a extra subtask..Please advice?

**Comment by mindrootstech** [comment]
Yes Marco,
We can create a sub-script to get lat long of the address for strip clubs and massage parlours and update their Lat long.
We will put in checks to see if the lat long for an address isnt found, we will pick the state/city lat long.

Effort to create the script and run it out will be $80.
Please confirm.

Also, the total effort for the data import of the 3 categories is $1010.
Can you please get that cleared out if all good.

Thanks

**Comment by mnights101** [comment]
Please make the following changes:

- [ ] I cannot login to admin in order to check backend work, admin is broken

- [ ] also lang file does not seem to be uploaded as many references to bnb and vacation rentals still present

- [ ] I tried to sign up and sms message reads bnbfusion in text message

- [ ] run script to update strip clubs and maasge lat/long for 80 approved

**Comment by mindrootstech** [comment]
All 4 pointers completed on live.
Please confirm and close.

**Comment by mnights101** [comment]
- [ ] when editing  FAQ in admin area to get rid of final bnb text I edited a few questions , however when I got to a particular question I get a 500 error message and previous edit of payment option reverted.

https://www.erosradar.com/admin/admin/help/update?id=5

- [ ] Rid bnb text in payout preferences



- [ ] Similar listing irelevant text footer



- [ ] Strip clubs in miami no results, nor any results for massage parlors

**Comment by mindrootstech** [comment]
Hi Marco,

Point 1, 2and 3 are fixed.
For point 4, i searched and got results for miami.
Screenshots attached.

Also, such textual edits will come up across the website and maybe we can create a sepertare task for these and keep a tab there rather than in this task.

Please confirm.
 
![Screenshot 2019-04-22 at 1 06 47 PM](https://user-images.githubusercontent.com/19343942/56489520-96be4200-64ff-11e9-9a00-c8e5dceb97a5.png)
![Uploading Screenshot 2019-04-22 at 1.06.57 PM.png…]()

**Comment by mnights101** [comment]
paid via mielestone 24 upwork
