### ISSUE TITLE
fix list (add escort process)

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#20]
Please fix: 

- [ ] Hair color options add:
- Bald
- Black
-Blonde
-Brown
- Brunette
- Dark Brown
- Dirty Blonde
- Gray

- [ ] Under eyes remove
-Dark Brown Hair
- Light brown hair

- [ ] Field Labeled Type: Change to Ethnicity

- [ ] On escorts profile in public view, it reads, stay here and leave host their first review
Please this to "Visit Provider to leave a their first review here"

**Comment by subodhsri1** [comment]
Hourly Estimate : 4.5 Hours

**Comment by mindrootstech** [comment]
Marco,
This task is already completed.

**Comment by mnights101** [comment]
Done
