### ISSUE TITLE
4. Add Listing Process

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#4]
1. - [ ] The providers will be able to add a listing for a fee of 9.99 USD, They will have a wallet. they can add money to their wallet with a gift card, or crypto, or paypal (if paypal selected instruct them to send money to email carolina.f@tuta.io with invoice #)

2 - [ ] listings will be posted in ascending order by date ( in other words each ad will be moved down the older it is and new ads will be listed first.

**Comment by mindrootstech** [comment]
As discussed, the wallet wont be used in the process.
The flow will be:
1. User will create an account
2. He will click on Add a listing, select his category, input all fields acc to selected category split in sections like current process and save his listing in disabled state
3. At the end, we will show him the payment amount and options - Crypto or Paypal.
4. Once payment is confirmed, his listing will become active.
5. If payment fails for some reason, next time when he logs in, we will show him a notification on the top saying Pay to activate your listing and on click, take him to payment page again.

+ sorting of listings in search will be changed to by location and latest first.

NOTE:
A. Right now, we don't have any Gift card module. So that will be an entirely seperate flow where a backend Gift card generation module will have to be created as well.
B. For paypal, we will directly implement Paypal checkout. Why do we need user to manually send payment.

Effort:
For the entire process, it will be a cost of $350
For the Gift card module, additional cost of $200

Please confirm.

**Comment by mnights101** [comment]
Manik,

The gift card is issued by third parties, not by us. That is why I stated we need a wallet. Because there will be allot of payments offline and we need to be able to add credit to advertisers account in order for them to use the credit to place ads.

Please adjust your quote accordingly....

**Comment by mnights101** [comment]
for example of gift card credit use and credit use please view https://my.cityxguide.com/login/

**Comment by mindrootstech** [comment]
I understand.
But if Gift cards are issued by 3rd party, then how will we be validating them in our system to give credits to the user's wallet to be used on submit listings?

**Comment by mindrootstech** [comment]
As per our discussion, new flow for task will be:
1. User will create account and wallet will be in his profile
2. In profile, we will give option to top up wallet via: Crypto, Paypal or manually submit voucher code
3. In backend, you will recieve requests for vouchers, you will accept/reject them and add credits to user's account
4. User will click on Add a listing, select his category, input all fields acc to selected category split in sections like current process and save his listing in disabled state.
5. At the end, we will show him the payment amount and options - Wallet, Crypto or Paypal.
6. Once payment is confirmed, his listing will become active.
7. If payment fails for some reason, next time when he logs in, we will show him a notification on the top saying Pay to activate your listing and on click, take him to payment page again.4. On last step of add listing, user can either pay via wallet or paypal or crypto.

Updated effort to include all above tasks will be $500
Please approve.

**Comment by mindrootstech** [comment]
Task is completed and moved to live.
Please review.

**Comment by mnights101** [comment]
- [ ] get rid of icons and adjust text to "select category" instead of category and get rid of subtext as defined in image below
![delete -icons](https://user-images.githubusercontent.com/10249755/57086322-e1904480-6ccb-11e9-9863-1116c172ecf3.png)


- [ ] on 2nd page of listing process fix header and delete subtext, correct misspelled word and add tooltip as depicted in image below:
![2ndpage-adjustment](https://user-images.githubusercontent.com/10249755/57086861-ed303b00-6ccc-11e9-88c7-e1bcc3054a43.png)

- [ ] Page 3 of  listing  process correction listed in image below:
![page3-listing process-correct](https://user-images.githubusercontent.com/10249755/57087898-1e116f80-6ccf-11e9-9637-1ff48fbf3ae5.png)

- [ ]  On last page it says pay by wallet, instead this sould be listed as a drop down along with paypal, chain pay, if they select wallet from the drop down, it should then list how much is in there wallet or advice them there are not enough funds in wallet, In addition there should be a wallet page (If there are not funds in wallet, the text should read not enough funds in wallet, click here to fund your wallet (this link should ring them to the wallet page where they are presented with funding options as drop downs as they select an option instructions are displayed for each along with image upload button for receipts:
**Option one: Gift Card**
Instructions: 
Step 1: Order Physical Amazon Gift card (no digital)
Step 2: upload picture receipt for approval

**Option two: Western Union**
Instructions:
Warning " No Online Transfers, must be physical"
Step 1: Visit a western Union Store
Step 2 : Send money to Carolina Flores - Address: Calle 22 Rudy X  | Country: Dominican Republic- Province: La Vega Zip -51000  : Phone 809-429-3949
Step 3 : Under Notes include your email address and username you use to login to our system
Step 4: Upload your receipt (must include MTCN, senders full name, city, & country

**Comment by mindrootstech** [comment]
These feedback have been implemented.
Please review and update.

**Comment by mnights101** [comment]
1. Description section : Please change this text "Tell clients about your space
Every space on Erosradar is unique. Highlight what makes your listing welcoming so that it stands out to guests who want to stay in your area." To this " Tell clients about you, every ad on eros radar is unique. Highlight what makes your listing special, so that it stands out to clients who want to do business with you."
2. Under services offered it is redundant to put rates for incall/outcall there. Rates should be set on the Pricing section, Here if outcall was selected then they should set rate for outcall in the pricing page, if incall was also selected in services offered then they should set incall rate on pricing page.
3. On wallet page when I select chainpay, then I go back to change to paypal the dropdown freezes and I can no longer use payment type dropdown, same issue occurs on the ads payment page
4. on dashboard page please adjust the following text:
![dasboard-text-change](https://user-images.githubusercontent.com/10249755/57236140-6217b380-6ff2-11e9-82ac-61d3254e0b03.png)

**Comment by mindrootstech** [comment]
Marco,

The asked edits have been completed.
Please check and review.

**Comment by mindrootstech** [comment]
Marco,

The Paypal flow has been added as discussed and module in the backend has been added to manually verify payments and approve listings.
Additional effort for this is $80.
Total task effort till now is $630.
Please check...

**Comment by mnights101** [comment]
paid via upwork milestone 27
