### ISSUE TITLE
Index adjustments and text changes

### ISSUE THREAD

**Issue by mnights101** [mnights101/erosradar#9]
- [x] Remove check in /check out boxes from index  /move to search criteria under massage and strip clubs, change text to check in/ select date check out/ select time | drop down values:(morning, afternoon, evening)

- [x] Remove List Your Place text / replace with: Place ads

- [x] Remove Where do you want to go / replace with: Enter a location to search

![eros-remove-check-in](https://user-images.githubusercontent.com/10249755/56760221-c2903080-6768-11e9-802a-2b395fd51172.png)

**Comment by mindrootstech** [comment]
Marco,

Above edits have been completed.
Please check and verify.
Effort: $60

**Comment by mnights101** [comment]
this task remains incomplete: "Remove List Your Place text / replace with: Place ads"

**Comment by mnights101** [comment]
complete, paid via upwork milestone 28
